#!/bin/sh

source ./params 2>/dev/null

#------------------------------------------------------------------------------
# Generate new device_xml links, no copy anymore
for file in /usr/local/addons/${ADDON_NAME}${FIRMWARE_DIR}/* ; do
    rm -f ${FIRMWARE_DIR}/$(basename $file)
    ln -s $file ${FIRMWARE_DIR}/$(basename $file)
    chmod 644 $file
done

#------------------------------------------------------------------------------
# Copy new image files
cp -ar www/config/img/devices /www/config/img/

chown root:root /www/config/img/devices/250/$DEVICE_IMG
chmod 755 /www/config/img/devices/250/$DEVICE_IMG
chown root:root /www/config/img/devices/50/$DEVICE_THUMB
chmod 755 /www/config/img/devices/50/$DEVICE_THUMB

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

#### string definition section commented out and retained for reference, no strings defined for test device

#------------------------------------------------------------------------------
### Edit stringtable_de.txt ###
# stringtable_deFile="/www/config/stringtable_de.txt"

# stringtable_deInsert="WEATHER|SKY_TEMPERATURE\t\${stringTableWeatherSkyTemperature}"
# if [ -z "`cat $stringtable_deFile | grep \"WEATHER|SKY_TEMPERATURE"`" ]; then
#     echo -e $stringtable_deInsert >> $stringtable_deFile
# fi


#------------------------------------------------------------------------------
### Edit German translate.lang.stringtable.js ###
# translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
# translate_deSearch="\"dummy\" : \"\","

# translate_deInsert="\n    \"stringTableWeatherSkyTemperature\" : \"Himmelstemperatur\","
# if [ -z "`cat $translate_deFile | grep \"stringTableWeatherSkyTemperature\"`" ]; then
# 	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
# fi


#------------------------------------------------------------------------------
### Edit English translate.lang.stringtable.js ###
# translate_deFile="/www/webui/js/lang/en/translate.lang.stringtable.js"
# translate_deSearch="\"dummy\" : \"\","

# translate_deInsert="\n    \"stringTableWeatherSkyTemperature\" : \"Sky Temperature\","
# if [ -z "`cat $translate_deFile | grep \"stringTableWeatherSkyTemperature\"`" ]; then
# 	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
# fi
